import type { Metadata } from "next";
import { BookOpenCheck, Code2, HeartHandshake, Lightbulb, Target, UsersRound } from "lucide-react";
import PageHero from "@/components/PageHero";
import Reveal from "@/components/Reveal";
import CTA from "@/components/CTA";

export const metadata: Metadata = { title: "About Us", description: "Learn about Vignesh Infinity Academy's student-focused school tuition and practical computer education.", alternates: { canonical: "/about/" } };
const values=[{icon:BookOpenCheck,title:"Clarity",text:"Teach concepts in simple, understandable steps."},{icon:UsersRound,title:"Attention",text:"Support students according to their current level."},{icon:Target,title:"Consistency",text:"Use regular practice, revision and feedback."},{icon:Code2,title:"Practical skills",text:"Connect computer learning with real tasks and projects."},{icon:Lightbulb,title:"Curiosity",text:"Encourage students to ask questions and understand why."},{icon:HeartHandshake,title:"Affordability",text:"Keep quality learning accessible to more families."}];
export default function AboutPage(){return <><PageHero eyebrow="About Us" title="Education that combines academic strength with digital confidence" description="Vignesh Infinity Academy provides school tuition and practical computer education through clear explanations, regular support and affordable learning options."/><section className="section-space"><div className="container grid items-center gap-14 lg:grid-cols-2"><Reveal><p className="eyebrow">Our purpose</p><h2 className="section-title mt-3">Help every learner move forward with confidence</h2><p className="section-copy mt-6">The academy began with a focus on school tuition and has expanded to computer, programming, web development, design and AI courses. The goal is not only to complete a syllabus, but to help learners understand, practise and apply what they learn.</p><p className="section-copy mt-4">Online Mathematics classes for 10th, 11th and 12th widen access across Tamil Nadu, while offline all-subject tuition for Classes 1–12 provides direct local support in the Rajapalayam region.</p></Reveal><Reveal><div className="rounded-[2rem] bg-gradient-to-br from-blue-700 to-indigo-900 p-8 text-white shadow-2xl sm:p-10"><p className="text-sm font-black tracking-[.18em] text-blue-200 uppercase">Our approach</p><blockquote className="mt-6 text-2xl font-black leading-relaxed">“Simple teaching, personal attention and practical learning can help students achieve more.”</blockquote><p className="mt-6 text-sm leading-7 text-blue-100">Vignesh Infinity Academy</p></div></Reveal></div></section><section className="section-space bg-slate-50"><div className="container"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{values.map((item,index)=>{const Icon=item.icon;return <Reveal key={item.title} delay={(index%3)*80}><div className="feature-card"><div className="grid size-12 place-items-center rounded-2xl bg-blue-600 text-white"><Icon/></div><h3 className="mt-5 text-xl font-black">{item.title}</h3><p className="mt-2 leading-7 text-slate-600">{item.text}</p></div></Reveal>})}</div></div></section><CTA/></>}
