import type { Metadata } from "next";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import PageHero from "@/components/PageHero";
import JsonLd from "@/components/JsonLd";
import { siteConfig, whatsappUrl } from "@/data/site";

export const metadata: Metadata = { title: "Contact", description: "Contact Vignesh Infinity Academy for school tuition, computer courses, fees and batch timings.", alternates: { canonical: "/contact/" } };
export default function ContactPage(){const schema={"@context":"https://schema.org","@type":"ContactPage",name:`Contact ${siteConfig.name}`,url:`${siteConfig.url}/contact/`};return <><JsonLd data={schema}/><PageHero eyebrow="Contact" title="Ask about courses, fees and current batch timings" description="Reach the academy directly by WhatsApp, phone or email. Mention the course and class level you are interested in."/><section className="section-space"><div className="container grid gap-8 lg:grid-cols-2"><div className="grid gap-5">{[
{icon:MessageCircle,title:"WhatsApp",value:"Fastest way to enquire",href:whatsappUrl,action:"Start WhatsApp chat"},{icon:Phone,title:"Phone",value:siteConfig.phoneDisplay,href:`tel:${siteConfig.phone}`,action:"Call the academy"},{icon:Mail,title:"Email",value:siteConfig.email,href:`mailto:${siteConfig.email}`,action:"Send an email"},{icon:MapPin,title:"Service location",value:siteConfig.location,href:"#",action:"Offline and online classes"}
].map(item=>{const Icon=item.icon;return <article key={item.title} className="feature-card flex gap-5"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white"><Icon/></div><div><p className="text-sm font-black text-blue-700">{item.title}</p><p className="mt-1 break-all font-black">{item.value}</p>{item.href!=="#"?<a href={item.href} target={item.href.startsWith('http')?'_blank':undefined} rel={item.href.startsWith('http')?'noreferrer':undefined} className="mt-2 inline-block text-sm font-bold text-slate-500 hover:text-blue-700">{item.action} →</a>:<p className="mt-2 text-sm text-slate-500">{item.action}</p>}</div></article>})}</div><div className="rounded-[2rem] bg-slate-950 p-8 text-white sm:p-10"><p className="eyebrow text-sky-300">Send these details</p><h2 className="mt-4 text-3xl font-black">Get a faster and clearer response</h2><p className="mt-4 leading-7 text-slate-300">When contacting the academy, include the student’s class or the computer course name, preferred online/offline mode and a suitable time for a callback.</p><div className="mt-8 space-y-4">{['Student name and class','Course you are interested in','Online or offline preference','Your area and suitable contact time'].map((item,index)=><div key={item} className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-600 font-black">{index+1}</span><span className="pt-1 font-bold text-slate-200">{item}</span></div>)}</div></div></div></section></>}
